language: node_js
node_js:
- '8'
sudo: required
addons:
  ssh_known_hosts:
  - secure: 1iNLPF/RwELquiEH1j58pMwzpfK+zEr21fM+PIhPFkAWtniEWtyTRkxvXkssNYB3UpPPyQ1y5Zf/uPL6l0X6W3GN7c2am/nahdE0kV2an4+qvUhqJTTQR/5Xb9ZwnfeNtqPKj/ruGHzoIDNTX/LL9oipLavhqO9dPyW6vwgZHmeCNV/D3aGRgyVtVbOWPurytsK2QNbh6PPbcxoQWFeYkXj1wYcZoN0MnJ9AYxPE4UuECbygWx1xBtymMTeOPZKs1HcZisHj4PBGz68M6p9Objwxi6xLCNAWhT+ufEZ40L+r/HhzC7TjGesSYFPOLuIe6g8ySt4wCoj5YL+NGg8UyPYmi6ANRx1T0HrlQo9XAQwrKsGqHNtpCgUNMBlAN3O5RFhb66kdbZI1wIN8n5kaFJO+0kiBrcvr7+AjmjXBTqEKOlAloPiTDg6q+gn3Z0Iii0bjMBneAwC3PtFYkmOQQZd8vhvHipUDam6NtGoKzi/xMGy5ruNz6CpB61GhCn8AroCY/TSn32OMWKp6V2UoOyk7QfzeBOFt4Lmhcw3yxEwIYUBADk+7zR5aWD2Gq9IsoziNWiF0bCqIEVvkOzZ3Agab4sG8REFlnplPd1d7uELF2kFE9+5C7mCe0Gp5r/axxFuLB5paqtGLTPjppaZfGHIT0PG8XdlZk7Ik5nZq2/8=
env:
  global:
  - testvar="wtf"
  - secure: qCZd2Cg9dKMT7UY27EYk/omLC5WmUF6wcJXgdvTF82IVOYwc+Pdouo7PVV4LJDtMhAJsUnabnQki+m2hNuZjfzztQ8+cMOrQ6w3cmxfvKI10+KiZgJ3Ir5tUlaf9EZEt2AyjK08IOAf1dy8kGCqdmPryhL0GvuQ0I6fXCme/tWmeBSfV8LLZZFQspZWPAaS5q4A24ehQqCeoGUteU+N9cd8BbKgU7/aasEHOzvZ2VzjLe+PMjk/c8LFZ0MQ0/J/xcz5gNJ/sCZETpxEWEX3WKRNQQ0Wyu+rK3o/R2xzObbfytKDkmCalMuEUC1S7f5AC2ze+U+k4tPbbHiH0yK21LI4AbqaENSfEyhaQAOjbhKy9JfPzENwrDqcZQQky5owLiC7j9E2TGcX+HeCcCl/r5plPUHXh+ZgUq6hpaW/OuYkf41UtxdUhdPYOx1XZAvrGrbaeAba5zm+iKTc+oyhcBkYkrl8/xNPpKc0H7KtA4LI4fQRQDQrx2Z7p7mW9MPbSv3iLomOoMIk46+52i35sm2+J9ZcrnaiTQqxmvJpgQvjx7BHkACwE3N5VvhhFbkMTdLH3l3FrjAjkwi2sSOFCH04XZRUB+iR7sUX1d5BHKkkexR8ICMtaOg6lfMuJl4lR6QIVU5tv3vX16pJJSxj3SmhcIBASaQF1A/EaPd4ZxkE=
before_install:
- sudo apt-get install sshpass
before_script:
  matrix:
  - ls -alh
  - echo $testvar
  - echo $SECRETTROL
  - secure: yO10IR7cXOXvk45wsEvlbzcrTLRBDMM+/eoQ3J9BfFREjMf1/YttOXrHgoA37aq71C4SbK38cgY6ZsHMjgmkwSw5WdK/3SC/BNixlzPJKwA0ZegLonLVGC3FzA/KL15AVhZ8A1FWQ0UV4SSwUWsSqtyGqv90yiXE13sC56P81zXQA4FMjO1ms8xremgsdQHirIJ8NCCBqjLMzhV0svAoLToygLW9RldE0E0je0MslPpqE9VTtsCN2uBk5qn0vW8/JclC4wHw+9+cp1MG0UOadf0Dxfvtu1Tzp+hEWzM9dFmL0IIwMRl03bdQowVjTWSYp3KJjyzTSOuZpyoE7id4PFDyBsufSWZJMr5nniA1fzqUpfk97YDxwZQCQpzv2ElFT1fqVhoKygUI8aYNbCqMxF8dXw+uxs/sOocsxdyu/iEAt9S5Hdm+vwYl9iR3PlSRwglTP+UZShsSJaN5yWGxrtUCSDzwuq8kYEMgqhHo4s2equesgyLGkRnvl6ZfrMawUzqnHCqqWGmDMyWPG5R5JJTtm9+Lar/zQJV9CwGC7P9oxg+wCY5wf4b11Brzl5QzyNSFCS6UAaumtJb4LN85WYq74cwdRIUogW+kDXWOl7v7tJ5a89vp+E0LSvLxdevtWHpoJMn40wNWWwAZ2VIbg+v6HgAVmLEERL6X75i8Xog=
  - sleep 5
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
cache:
  directories:
  - node_modules
