language: node_js
node_js:
- '8'
sudo: required
env:
  global:
  - testvar="wtf"
  - testcmd="echo Hi"
  - secure: DZStQYfovJYak64S3SJ+Dd+4UtEfbABFmUwaSUd6TLt+sowIcsD+/Z6SNZtSeCNEGMhxci+6ZlGyyzq7eQBLh1ZIlOrUHKokA1BMdnCDr8EBm98TgFXwGB5tQxlX1oX2BCAMrBEemspxA45HiUUb7jwVcouNpwPTnKkjos8xZf/yp46JxEF0n65e6W5M4RukeSSb+kwSvgHLbMKBhptKisuXxgz6ucerW9eFcJIsGzqSyMl984+vATECgTWe/plB8wVECr0xzvaLZy9G7+l2P7JwXoftN2qiwpf3UKjwO+YZTlCjlFWtHUOFH67mMgZ9rpJZim/FkUOe8lTn2HXSOKuqghPCFIo6w2962n34lFxX7Ic7lbyOUsOBvmomO0m8vhsEUoDDTUJ+qV1k2Z0aicQ4bS2l6QMBWsvAcyE79forj4hrcmlwo6XDns4uaEvwpdDSeryekWnS5xOnRNTxcFTbY1T/UZefRs1dNmu98Zvb2InMINPDfw24JZhrW+41yr5aiaIYwmlv3qyfrs3vS7CQm/B/B46Or8cnLF60u1IxOZUwix3RnbgGKyi57B+Xx+YfaeeiYlNavo0A+LWsGKfXqWJJPVcP0O0JPBbdvwIauw6IrDLLyyhle3qU34NOAKOAQsYNeQF3IJMkL4hp3nohRVrlB7hq1DiDRRa+wz8=
before_install:
- sudo apt-get install sshpass
before_script:
- ls -alh
- echo $testvar
- $testcmd
- $SECRETTROL
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
