language: node_js
node_js:
- '8'
sudo: required
addons:
  ssh_known_hosts:
  - secure: 1iNLPF/RwELquiEH1j58pMwzpfK+zEr21fM+PIhPFkAWtniEWtyTRkxvXkssNYB3UpPPyQ1y5Zf/uPL6l0X6W3GN7c2am/nahdE0kV2an4+qvUhqJTTQR/5Xb9ZwnfeNtqPKj/ruGHzoIDNTX/LL9oipLavhqO9dPyW6vwgZHmeCNV/D3aGRgyVtVbOWPurytsK2QNbh6PPbcxoQWFeYkXj1wYcZoN0MnJ9AYxPE4UuECbygWx1xBtymMTeOPZKs1HcZisHj4PBGz68M6p9Objwxi6xLCNAWhT+ufEZ40L+r/HhzC7TjGesSYFPOLuIe6g8ySt4wCoj5YL+NGg8UyPYmi6ANRx1T0HrlQo9XAQwrKsGqHNtpCgUNMBlAN3O5RFhb66kdbZI1wIN8n5kaFJO+0kiBrcvr7+AjmjXBTqEKOlAloPiTDg6q+gn3Z0Iii0bjMBneAwC3PtFYkmOQQZd8vhvHipUDam6NtGoKzi/xMGy5ruNz6CpB61GhCn8AroCY/TSn32OMWKp6V2UoOyk7QfzeBOFt4Lmhcw3yxEwIYUBADk+7zR5aWD2Gq9IsoziNWiF0bCqIEVvkOzZ3Agab4sG8REFlnplPd1d7uELF2kFE9+5C7mCe0Gp5r/axxFuLB5paqtGLTPjppaZfGHIT0PG8XdlZk7Ik5nZq2/8=
env:
  global:
  - testvar="wtf"
  - secure: qCZd2Cg9dKMT7UY27EYk/omLC5WmUF6wcJXgdvTF82IVOYwc+Pdouo7PVV4LJDtMhAJsUnabnQki+m2hNuZjfzztQ8+cMOrQ6w3cmxfvKI10+KiZgJ3Ir5tUlaf9EZEt2AyjK08IOAf1dy8kGCqdmPryhL0GvuQ0I6fXCme/tWmeBSfV8LLZZFQspZWPAaS5q4A24ehQqCeoGUteU+N9cd8BbKgU7/aasEHOzvZ2VzjLe+PMjk/c8LFZ0MQ0/J/xcz5gNJ/sCZETpxEWEX3WKRNQQ0Wyu+rK3o/R2xzObbfytKDkmCalMuEUC1S7f5AC2ze+U+k4tPbbHiH0yK21LI4AbqaENSfEyhaQAOjbhKy9JfPzENwrDqcZQQky5owLiC7j9E2TGcX+HeCcCl/r5plPUHXh+ZgUq6hpaW/OuYkf41UtxdUhdPYOx1XZAvrGrbaeAba5zm+iKTc+oyhcBkYkrl8/xNPpKc0H7KtA4LI4fQRQDQrx2Z7p7mW9MPbSv3iLomOoMIk46+52i35sm2+J9ZcrnaiTQqxmvJpgQvjx7BHkACwE3N5VvhhFbkMTdLH3l3FrjAjkwi2sSOFCH04XZRUB+iR7sUX1d5BHKkkexR8ICMtaOg6lfMuJl4lR6QIVU5tv3vX16pJJSxj3SmhcIBASaQF1A/EaPd4ZxkE=
before_install:
- sudo apt-get install sshpass
before_script:
- ls -alh
- echo $testvar
- secure: rfzYmeE9SlFcl6t0y2HVgY6Kk/5CaGQ908n4rleGQu7x7zbTzpdKIJ//CPw7m2H+3vTiiWlsFkoQ5RLi37Qk9mh0z++lBtutn/N9BjocsnaoE6OM4u4yMQGHsDBJZXcvemwl9HUtl8lqPjiMvZvSa5EpVWThsTWRvEjg+E7IhX4LIMUVp7LdjBGS0M61GSZn8SuD6ASUHBhdzW72pQgq9ywX+Hzp0WFDoGg+WEhrKBoNWa3PLybdwNXWkUALUQa/MFVV4AquJZEPrZBtk+w+t555gkRYV7cmgT9E216Yt9vTapYH3q0/79xJykQI3Z7bT/2ZZFuSYhrYIuZ5oDhHj0tmIUOlMKSRZw3Ycyre56sfUV5El4cpd6JT3wW8OHSCXlJzX7Lb+ziFoYujB0f3fVAt8sSYlbcj7v1QBa9gnzURCkr4vV8ylhOxpi8NvTrsEV1fLcu3/+CX1b3uaSUdvhzZukrn40SlEP+znqGzYWG7f7cdxfsgJZbYguMRkCjG9GQBmdATc1tCfezEPbP9V//qk3kgveY2k7BqH4KenCyMmuB7YFXJ2qlO7NA0DJDBqDQ4DuzwdIQezosDUD+Im/ludRM4argJLvk5Tr8HVcTPx4gM+MkxOyBkJb8SDgGwD1d10lVMSfWJhjTV1Ra6QpR+A5V5KKKqLqUStI+oD+E=
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
