language: node_js
node_js:
- '8'
sudo: required
env:
  global:
  - testvar="wtf"
  - testcmd="echo Hi"
  - secure: RNDSaMm2pmryH1U3GXPzJJlsnizP2CpIcNEi+x585mEqejxGxI+ZE2bjK46wnFzcfr3Nw2rOqHggYDXQVxQGbIFKLmfRm5Vx/9/eAUzGsMEgywy+KVWZ+nF9cRMI1OIvwtYZUMCyeOcqVOHyRGTJW5Xzy/wrS8zVsdqHbOEnaHlWMLJjhCRysW65uQaml61G4Cm6CIdMwSxCsN6W9X9mniGW5/LgtmzHqiX/2oHgrFwUh2ES65UZJhulzbje44Vv1tA9woNknTIuXYDzZxgA/QY8pCfOmGSM2NW82IjDozzkU0f6ZeiG5wz+KZ4PE241tpfL01G2VyO8qOUi5oYEyIDDVJyvketjCVlQh9oq5dLHQA8WWMS0WCx93YFpRT/rhN9xiP7BdHzH2gJ43/oDJ+l4LypcCZVw6VSL5nfQvDBu94wcbPx3yEcyJzffhWk24eGMqJtL8YLLbrpZ8q04cYiliBFT6Pwo+wPQiLrDtfKI6gRqQ2KUIYYG0pOfYQ9/uxcyl1bUxmF1HJJruPX+Gb/FKKcTePdW5NapCc6lOHyDkikV882L9bh3T8PibB4wbVLetx0IKALgB1gVQBPiIXQGK0PFLelO9HhRyR+IF8gh6Kowc1lfKJADyg6fMOV2vJGLucZSkk/C0FRP3/thNpb7Jk6foYEqORVEviWVWpw=
before_install:
- sudo apt-get install sshpass
before_script:
- ls -alh
- echo $testvar
- "$testcmd"
- "$SECRETTROL"
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
