language: node_js
node_js:
- '8'
sudo: required
env:
  global:
  - testvar="wtf"
  - testcmd="echo Hi"
  - secure: wLB7h7f3cDy69QDI/EKHItGUaj3WbJdHSfnXMeDC5j1HzuySeEyZN5dMSeRnDNXrkiBmXYHTd/bOPT7akzXSjcHlEmYG7ZT88en5lpSQfJ0r33/FRXZrH/H7e0HLQosMtAg2Bs40LRkxjd9idJD9NpUHsf7U4CA2iixXeFNhrkDRToXEOJRnF84lo8bGxozqPQM8qLvQj2uHIfUe9JOv6SZPsgBQTvgSu1dPFfiN/t9kBhEUPWMUyqeNIRMYYVwxvFYO0f618TakEBtS/Ze9f8G8F6ZJnswjRRZw1iTFqV2yxyeYh6k3+og/sqTKEKXLfgL5z+gJAnJFCfdosAKSCMfwLnGdDX1PIDUnA7CHVjBpIoV0LBoG6ia9vnIsDlSKEl4Jf4GFUxQJcvet5i+qt688AfMhf3c73FH90awySN+9u+JBdJlsEyqwWDMkzRcFcfbOjuJF5ta5zez/iORRfgZmVn5+8tx5+4dmW3fmhAdGmtEoX69U8U+etpajHXR2mIjyN3DZ1rEdmq7wYg0p9xYW92v2wItN+vfot57roCXOcFzHRVBpqrbXuwf6u5NT0ptsZNJ94cS3TgLRfgfZC4UWmdZaWmWi/I2fzaAn4aWlBNg7e3Ojdr2MxwP9gO2Thwvu8x2gF3/Y1GroSUlXS2vyOog77+IJoTtbD4TgmXM=
  - secure: VItUyUxJ8T5rp6iYZq1JFii9naj0M56YGK1n0QUgtrGGqtCxKr0FIINg8eVIEy7x7jRNFDs/EqnU5x9fSh22Ll0+4+ETALaYwgmMXeeL5VC550VcDn+nyAz5R75ZMTG1FZjpbSXG/POJMbcP2sfOJUMIdNc5vLO69uTfN79339su8E6j3tVTLeP5IrdWZyZX4BHGt4iTAV622baDwjFxSAGkhVwtFaY4/aBKZs8nmcHjh/QZPZkX7XJuceqYO5s/i5ow1CaIWVtMwXfMfew64Syo30narpAEsxpz+Vtg0DqyPQkU/tbh7U3ctpX2JqFiCNQhVhRRyS/RhNDLSZCRumPAaY7XLxV5Izuuby8vNB7EAEc86nOSXkZIS6V51/DPlb5wWVoF4nJWaVwkluLPMrg4/2g/W5rTORNjcY5G1NcuPbrbWbnI9FKBP5dEaDbppaSKF/TELO5/cofYLUp/QEmk0gMYFNMKHiJshDK+4O2Wc9QpNy0bY66vfyuhlqwG/KGQzOT4tLsZ5zouRUmBrkXFRieXwdotrCfwqR0xgmWn4cla/SYYWZl1mAHkeoa8q1xUe0b+GMYsaPopyQ3HtCB50hZz3aKSFJSzVD0tZ8IAebD6ssStwlYO09xi7hNzhGEHl9QFCl8klVK6iG9nntj0SnLosmuNM924ZkB6dJk=
before_install:
- sudo apt-get install sshpass
before_script:
- ls -alh
- echo $testvar
- "$testcmd"
- "$SECRETTROL"
- echo "$SECRETSTR"
- sleep 5
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
